module.exports = {
    register: '注 册',
    login: '登 录',
    logout: '登 出',
    username: '用户名',
    password: '密  码',
    search: '查 找',
    op: '操 作',
    delete: '删除',
    modify: '修改',
    addbook: '添加新书',
    ok: '确 定',
    continue: '继 续',
    reset: '重 置',
    back: '返 回',
    bookid: '序 号',
    bookname: '书 名',
    bookseries: '系 列',
    bookauthor: '作 者',
    barcode: '条 码',
    bookowner: '所有人',
    bookcreate: '上架时间',
    bookstatus: '当前状态',
    booklastmodified: '最后更新时间',
}